name: Submit package to Windows Package Manager Community Repository 

on:
  release:
    types: [published]

env:
  packageFileName: LegendUtil_Setup.exe
  packageId: femtoCommunity.LegendUtil
  
jobs:
  
  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Submit package to Windows Package Manager Community Repository
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
          $installerUrl = $github.release.assets | Where-Object -Property name -match ${env:packageFileName} | Select -ExpandProperty browser_download_url -First 1
          .\wingetcreate.exe update ${env:packageId} -s -v $github.release.name -u $installerUrl -t ${{ secrets.Project_PAT }}
