name: Build Nightly

on:
  push:
    branches: [ "dev" ]

env:
  project-name: LegendUtil
  produire-url: https://produ.irelang.jp/downloads

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create Directory
        shell: pwsh
        run: |
          New-Item -ItemType Directory "\rdr"
          New-Item -ItemType Directory "$env:RUNNER_TEMP\Source"
          New-Item -ItemType Directory "$env:RUNNER_TEMP\Source\LegendUtil"
          New-Item -ItemType Directory "$env:RUNNER_TEMP\Source\Releases_Nightly"
          New-Item -ItemType Directory "$env:RUNNER_TEMP\Build"

      - uses: actions/checkout@v4
        with:
          path: ${{ runner.temp }}\Source\LegendUtil

      - uses: actions/checkout@v4
        with:
          ref: releases/nightly
          path: ${{ runner.temp }}\Source\Releases_Nightly

      - name: Cache Produire
        id: cache-produire
        uses: actions/cache@v3
        env:
          cache-name: cache-produire
        with:
          path: \rdr
          key: ${{ env.cache-name }}-${{ vars.PRODUIRE_VERSION_MAJOR }}.${{ vars.PRODUIRE_VERSION_MINOR }}.${{ vars.PRODUIRE_VERSION_BUILD }}

      - if: ${{ steps.cache-produire.outputs.cache-hit != 'true' }}
        name: Download Produire
        continue-on-error: true
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "${{ env.produire-url }}/${{ vars.PRODUIRE_VERSION_MAJOR }}.${{ vars.PRODUIRE_VERSION_MINOR }}/produire-${{ vars.PRODUIRE_VERSION_MAJOR }}.${{ vars.PRODUIRE_VERSION_MINOR }}.${{ vars.PRODUIRE_VERSION_BUILD }}.zip" -OutFile "$env:RUNNER_TEMP\rdr.zip"
          $zipfilePath="$env:RUNNER_TEMP\rdr.zip"
          $destinationUnzipPath="\rdr"
          & ${env:ProgramFiles}\7-Zip\7z.exe x $zipfilePath "-o$($destinationUnzipPath)" -y
          Remove-Item -Path "\rdr.zip"

      - name: Set Git Config
        shell: pwsh
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Run Builder
        shell: pwsh
        run: |
          Start-Process -Wait -NoNewWindow -FilePath "\rdr\pconsole.exe" -ArgumentList "$env:RUNNER_TEMP\Source\LegendUtil\Scripts\NightlyBuilder_Actions.rdr"
